name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Le type de machine virtuelle à utiliser basé sur la matrice ci-dessus
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -B build

    - name: Build project
      run: cmake --build build --config Debug

    - name: Run tests
      run: ctest --test-dir build -C Debug --output-on-failure