name: C++ Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt-version: ['6.7.1']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ÉTAPE 1 : Installer les dépendances spécifiques à l'OS
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build libgl1-mesa-dev libxcb-xinerama0 libxkbcommon-x11-dev libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0

    # ÉTAPE 2 : Mettre en cache les fichiers Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/qt-cache
        key: ${{ runner.os }}-qt-${{ matrix.qt-version }}

    # ÉTAPE 3 : Installer Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt-version }}
        arch: ${{ runner.os == 'Windows' && 'win64_mingw' || '' }}
        dir: ${{ runner.temp }}/qt-cache
        # On ajoute "cache: 'true'" pour une meilleure intégration avec l'étape de cache
        cache: 'true'
        cache-key-prefix: ${{ runner.os }}-qt-${{ matrix.qt-version }}

    # --- VÉRIFIEZ ATTENTIVEMENT CETTE PARTIE ---

    # ÉTAPES DE BUILD POUR LINUX / MACOS
    - name: Configure, Build and Test (Unix)
      if: runner.os != 'Windows'
      run: |
        cmake -B build \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_PREFIX_PATH=${{ env.QT_ROOT_DIR }} \
          -D BUILD_TESTING=ON \
          -G Ninja
        
        cmake --build build --parallel
        
        ctest --test-dir build --output-on-failure

    # ÉTAPES DE BUILD POUR WINDOWS
    - name: Configure, Build and Test (Windows)
      if: runner.os == 'Windows'
      # Cette ligne est CRUCIALE pour Windows
      shell: msys2 {0}
      run: |
        cmake -B build \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_PREFIX_PATH=${{ env.QT_ROOT_DIR }} \
          -D BUILD_TESTING=ON \
          -G Ninja
        
        cmake --build build --parallel

        ctest --test-dir build --output-on-failure